server:
  port: 8080

spring:
  application:
    name: scheduler-admin
  datasource:
    url: jdbc:mysql://localhost:3306/distributed_scheduler?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

scheduler:
  core:
    base-url: http://localhost:8081
