server:
  port: 8082

spring:
  application:
    name: scheduler-worker
  datasource:
    url: jdbc:mysql://localhost:3306/distributed_scheduler?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

scheduler:
  rabbit:
    exchange: scheduler.job.exchange
    route-key: scheduler.job.route
    queue: scheduler.job.queue
    retry-exchange: scheduler.job.retry.exchange
    retry-route-key: scheduler.job.retry.route
    retry-queue: scheduler.job.retry.queue
    retry-delay-ms: 10000
  worker:
    id: worker-1
    address: 127.0.0.1:8082
  callback:
    host: 127.0.0.1
    port: 19090
